// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eUDrive.DataAccess.Context;

#nullable disable

namespace eUDrive.DataAccess.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20260502103228_AddAdvancedProductModel")]
    partial class AddAdvancedProductModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eUDrive.Domains.Entities.Product.DescriptionAdvanced", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("H")
                        .HasColumnType("int");

                    b.Property<int>("L")
                        .HasColumnType("int");

                    b.Property<int>("W")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DescriptionAdvacned");
                });

            modelBuilder.Entity("eUDrive.Domains.Entities.Product.ProductData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int?>("DescriptionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("eUDrive.Domains.Entities.Product.ProductDescriptionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("DescriptionAdvancedId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionAdvancedId");

                    b.ToTable("Description");
                });

            modelBuilder.Entity("eUDrive.Domains.Entities.Product.ProductImgData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductDataId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductDataId");

                    b.ToTable("ProductImgs");
                });

            modelBuilder.Entity("eUDrive.Domains.Entities.Product.ProductData", b =>
                {
                    b.HasOne("eUDrive.Domains.Entities.Product.ProductDescriptionData", "Description")
                        .WithMany()
                        .HasForeignKey("DescriptionId");

                    b.Navigation("Description");
                });

            modelBuilder.Entity("eUDrive.Domains.Entities.Product.ProductDescriptionData", b =>
                {
                    b.HasOne("eUDrive.Domains.Entities.Product.DescriptionAdvanced", "DescriptionAdvanced")
                        .WithMany()
                        .HasForeignKey("DescriptionAdvancedId");

                    b.Navigation("DescriptionAdvanced");
                });

            modelBuilder.Entity("eUDrive.Domains.Entities.Product.ProductImgData", b =>
                {
                    b.HasOne("eUDrive.Domains.Entities.Product.ProductData", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductDataId");
                });

            modelBuilder.Entity("eUDrive.Domains.Entities.Product.ProductData", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
